package my.com.m1.onegold.shared.viewmodel.model

data class UserModel(
    val id: String,
    val fullName: String = "John Doe",
    val email: String,
    val accountCode: String,
    var bankAccName: String,
    var bankAccNumber: String,
    var bankId: String,
    val city: String,
    val referralBranchCode: String?,
    val referralSalespersonCode: String?,
    val occupation: String?,
    val occupationCategory: OccupationModel?,
    val hostedApplicationId: String,
    val myKadNumber: String,
    val nextOfKeenAddress: String,
    val nextOfKeenEmail: String,
    val nextOfKeenFullName: String,
    val nextOfKeenMyKadNumber: String,
    val nextOfKeenPhone: String,
    val nextOfKeenRelationship: String,
    val phoneNumber: String,
    val postcode: String,
    val preferredLang: String,
    val state: String,
    val streetLine1: String,
    val streetLine2: String
)